encouragements = [
    'You got this.',
    'Sending major good vibes your way.',
    'I know this won’t be easy, but I also know you’ve got what it takes to get through it.',
    'Time to go kick cancer’s ass!',
    'Sending you good thoughts—and hoping you believe in yourself just as much as I believe in you.',
    'Be good to yourself. And let others be good to you, too.',
    'This is what you’re going through, not who you are.',
    'You are amazing for facing this with so much courage and hope.',
    'You’re being so strong—and patient. Keep the faith. Things are going to start looking up soon.',
    'This is tough, but you’re tougher.',
    'Even when you might not feel it, you’ve got the strength to get through.',
    '“I’m so sorry you’re going through this.',
    'This totally sucks, but you totally don’t suck.',
    'It’s okay not to be okay.',
]
