quotes = [
    '**C1: NU INCERCATI**\nomul care lupta pentru ce vrea, nu renunta niciodata, iar in cele din urma isi indeplineste cele mai nebunesti visuri.',
    '**C1: NU INCERCATI**\nomul fericit pur si simplu este fericit, esti sau nu esti.',
    '**C1: NU INCERCATI**\ncheia unei vieti mai bune nu este sa-ti pese de mai multe lucruri, ci de mai putine, adica de ce este adevarat, urgent si important.',
    '**C1: PERFIDUL CERC VICIOS**\ndin cauza asta e important sa nu te ingrijorezi. nepasarea va salva lumea. o va salva daca acceptam ca e o lume nebuna si ca e in regula sa fie asa, pentru ca asa a fost mereu si asa va fi de-acum inainte.',
    '**C1: PERFIDUL CERC VICIOS**\nn-ati observat oare ca, atunci cand va pasa mai putin, in legatura cu orice, sunteti mai eficienti? ',
    '**C1: PERFIDUL CERC VICIOS**\ntot ceea ce este important in viata se castiga prin depasirea experientei negative aferente.',
    '**C1: ARTA SUBTILA A NEPASARII**\na nu-ti pasa nu inseamna a fi indiferent, ci a te simti confortabil cu faptul ca esti diferit.',
    '**C1: ARTA SUBTILA A NEPASARII**\nnu se poate sa nu-ti pese de nimic. trebuie sa-ti pese de ceva.',
    '**C1: ARTA SUBTILA A NEPASARII**\n ca sa nu-ti pese de obstacole, trebuie sa-ti pese de ceva mai important decat obstacolele cu care te confrunti',
    '**C1: ARTA SUBTILA A NEPASARII**\ncand omul nu are nicio problema, mintea gaseste automat o cale de-a inventa niste probleme.',
    '**C1: ARTA SUBTILA A NEPASARII**\nfiindca, daca nu gasesti acel lucru semnificativ, vei ajunge sa te consumi din princina a tot felul de nimicuri inutile.',
    '**C1: ARTA SUBTILA A NEPASARII**\nomul ajunge la maturitate in momentul in care invata sa se ingrijoreze doar pentru lucrurile care merita.',
    '**C1: BINE, MARK, SI TOTUSI CARTEA ASTA DESPRE CE NAIBA E?**\nin definitiv, suferinta poate fi depasita doar dupa ce inveti sa cum s-o suporti.',
    '**C1: BINE, MARK, SI TOTUSI CARTEA ASTA DESPRE CE NAIBA E?**\ncartea asta, in schimb, va va transforma durerea intr-o unealta, trauma intr-o forta, iar problemele in probleme mai acceptabile.',
    '**C2: FERICIREA ESTE O PROBLEMA**\nideea e ca nimeni nu scapa de suferinta.',
    '**C2: FERICIREA ESTE O PROBLEMA**\ndurerea si pierderea sunt inevitabile, asa ca n-are niciun rost sa incercam sa le opunem rezistenta.',
    '**C2: AVENTURILE LUI PANDA INCOMODUL**\nsuntem programati sa fim nemultumiti de ceea ce avem si multumiti doar de ceea ce nu avem.',
    '**C2: AVENTURILE LUI PANDA INCOMODUL**\ndurerea, in toate formele ei, este cea mai eficienta metoda prin care corpul nostru indeamna la actiune.',
    '**C2: AVENTURILE LUI PANDA INCOMODUL**\nde aceea, evitarea durerii si cautarea placerii nu sunt intotdeauna benefice, din moment ce durerea poate fi uneori de o importanta capitala pentru starea noastra de bine.',
    '**C2: AVENTURILE LUI PANDA INCOMODUL**\ndurerea emotionala provocata de respingere sau esec ne invata sa nu repetam aceleasi greseli in viitor.',
    '**C2: AVENTURILE LUI PANDA INCOMODUL**\nrezolvarea unei probleme duce pur si simplu la aparitia altei probleme.',
    '**C2: AVENTURILE LUI PANDA INCOMODUL**\nsa nu speri la o viata fara probleme. nu exista asa ceva. poti, in schimb, spera la o viata plina de probleme benefice.',
]