quotes = [
    '**C1: NU INCERCATI**\nomul care lupta pentru ce vrea, nu renunta niciodata, iar in cele din urma isi indeplineste cele mai nebunesti visuri.',
    '**C1: NU INCERCATI**\nomul fericit pur si simplu este fericit, esti sau nu esti.',
    '**C1: NU INCERCATI**\ncheia unei vieti mai bune nu este sa-ti pese de mai multe lucruri, ci de mai putine, adica de ce este adevarat, urgent si important.',
    '**C1: PERFIDUL CERC VICIOS**\ndin cauza asta e important sa nu te ingrijorezi. nepasarea va salva lumea. o va salva daca acceptam ca e o lume nebuna si ca e in regula sa fie asa, pentru ca asa a fost mereu si asa va fi de-acum inainte.',
    '**C1: PERFIDUL CERC VICIOS**\nn-ati observat oare ca, atunci cand va pasa mai putin, in legatura cu orice, sunteti mai eficienti? ',
    '**C1: PERFIDUL CERC VICIOS**\ntot ceea ce este important in viata se castiga prin depasirea experientei negative aferente.',
    '**C1: ARTA SUBTILA A NEPASARII**\na nu-ti pasa nu inseamna a fi indiferent, ci a te simti confortabil cu faptul ca esti diferit.',
    '**C1: ARTA SUBTILA A NEPASARII**\nnu se poate sa nu-ti pese de nimic. trebuie sa-ti pese de ceva.',
    '**C1: ARTA SUBTILA A NEPASARII**\n ca sa nu-ti pese de obstacole, trebuie sa-ti pese de ceva mai important decat obstacolele cu care te confrunti',
    '**C1: ARTA SUBTILA A NEPASARII**\ncand omul nu are nicio problema, mintea gaseste automat o cale de-a inventa niste probleme.',
    '**C1: ARTA SUBTILA A NEPASARII**\nfiindca, daca nu gasesti acel lucru semnificativ, vei ajunge sa te consumi din princina a tot felul de nimicuri inutile.',
    '**C1: ARTA SUBTILA A NEPASARII**\nomul ajunge la maturitate in momentul in care invata sa se ingrijoreze doar pentru lucrurile care merita.',
    '**C1: BINE, MARK, SI TOTUSI CARTEA ASTA DESPRE CE NAIBA E?**\nin definitiv, suferinta poate fi depasita doar dupa ce inveti sa cum s-o suporti.',
    '**C1: BINE, MARK, SI TOTUSI CARTEA ASTA DESPRE CE NAIBA E?**\ncartea asta, in schimb, va va transforma durerea intr-o unealta, trauma intr-o forta, iar problemele in probleme mai acceptabile.',
    '**C2: FERICIREA ESTE O PROBLEMA**\nideea e ca nimeni nu scapa de suferinta.',
    '**C2: FERICIREA ESTE O PROBLEMA**\ndurerea si pierderea sunt inevitabile, asa ca n-are niciun rost sa incercam sa le opunem rezistenta.',
    '**C2: AVENTURILE LUI PANDA INCOMODUL**\nsuntem programati sa fim nemultumiti de ceea ce avem si multumiti doar de ceea ce nu avem.',
    '**C2: AVENTURILE LUI PANDA INCOMODUL**\ndurerea, in toate formele ei, este cea mai eficienta metoda prin care corpul nostru indeamna la actiune.',
    '**C2: AVENTURILE LUI PANDA INCOMODUL**\nde aceea, evitarea durerii si cautarea placerii nu sunt intotdeauna benefice, din moment ce durerea poate fi uneori de o importanta capitala pentru starea noastra de bine.',
    '**C2: AVENTURILE LUI PANDA INCOMODUL**\ndurerea emotionala provocata de respingere sau esec ne invata sa nu repetam aceleasi greseli in viitor.',
    '**C2: AVENTURILE LUI PANDA INCOMODUL**\nrezolvarea unei probleme duce pur si simplu la aparitia altei probleme.',
    '**C2: AVENTURILE LUI PANDA INCOMODUL**\nsa nu speri la o viata fara probleme. nu exista asa ceva. poti, in schimb, spera la o viata plina de probleme benefice.',
    '**FERICIREA VINE DIN REZOLVAREA PROBLEMELOR**\nproblemele nu se opresc niciodata; doar se modifica si/sau devin mai complexe.',
    '**FERICIREA VINE DIN REZOLVAREA PROBLEMELOR**\nfericirea vine din rezolvarea problemelor',
    '**FERICIREA VINE DIN REZOLVAREA PROBLEMELOR**\ndaca eviti problemele sau simti ca nu ai nicio problema, atunci vei suferi.',
    '**FERICIREA VINE DIN REZOLVAREA PROBLEMELOR**\ndaca simti ca te confrunti cu probleme pe care nu le poti rezolva, vei fi la fel de nefericit.',
    '**FERICIREA VINE DIN REZOLVAREA PROBLEMELOR**\nn-o sa gasesti fericirea asteptandu-te intr-un loc, o idee, o slujba - sau intr-o carte.',
    '**FERICIREA VINE DIN REZOLVAREA PROBLEMELOR**\nsolutiile problemelor de azi reprezinta fundatia pe care cresc problemele de maine si asa mai departe.',
    '**FERICIREA VINE DIN REZOLVAREA PROBLEMELOR**\nfericirea autentica se naste atunci cand descoperi probleme care-ti plac si pe care le rezolvi cu placere.',
    '**FERICIREA VINE DIN REZOLVAREA PROBLEMELOR**\nnegand realitatea, sunt siliti sa se amageasca sau sa ignore realitatea. se pot simti bine pe termen scurt, dar chestia asta duce la o viata de nesiguranta, nevrotism si reprimare emotionala.',
    '**FERICIREA VINE DIN REZOLVAREA PROBLEMELOR**\nvictimele dau vina pe ceilalti sau pe imprejurari pentru problemele lor. se pot simti bine pe termen scurt, dar mentalitatea de victima duce la o viata dominata de sentimente de furie, de neajutorare si disperare.',
    '**FERICIREA VINE DIN REZOLVAREA PROBLEMELOR**\namintiti-va ca niciun om cu adevarat fericit nu are motive sa se aseze in fata oglinzii si sa-si spuna ca este fericit.',
    '**EMOTIILE SUNT SUPRAEVALUATE**\nemotiile sunt doar niste semnale biologice menite sa te impinga in directia schimbarilor benefice.',
    '**EMOTIILE SUNT SUPRAEVALUATE**\nemotiile negative sunt un imbold la actiune. cand le simtim, asta se intampla pentru ca trebuie sa facem ceva. ',
    '**EMOTIILE SUNT SUPRAEVALUATE**\nemotiile pozitive sunt recompensele actiunilor corecte. cand le simtim, viata pare simpla, iar noi trebuie sa ne bucuram de ea. dupa care dispar, ca orice altceva, pentru ca apar, inevitabil, alte probleme.',
    '**EMOTIILE SUNT SUPRAEVALUATE**\nceva nu este bun doar pentru ca simtim noi ca este bun. la fel cum ceva nu este rau doar pentru ca noi simtim ca este rau.',
    '**EMOTIILE SUNT SUPRAEVALUATE**\ndin nefericire, sa nu acceptam emotiile negative inseamna sa nu acceptam o mare parte din mecanismul de feedback cu ajutorul caruia reusim sa rezolvam probleme.',
    '**EMOTIILE SUNT SUPRAEVALUATE**\ndurerea nu apare fara un scop, amintiti-va.',
    '**EMOTIILE SUNT SUPRAEVALUATE**\ndeciziile luate in baza intuitiei emotionale, fara ajutorul ratiunii, sunt aproape tot timpul gresite.',
    '**EMOTIILE SUNT SUPRAEVALUATE**\nemotiile nu dureaza. ce ne face fericiti azi n-o sa ne faca si maine, deoarece biologia noastra are intotdeauna nevoie de ceva mai mult.',
    '**EMOTIILE SUNT SUPRAEVALUATE**\norice implica un sacrificiu - orice ne face sa ne simtim bine ne va face, inevitabil, sa ne simtim rau. ce castigam e totuna cu ce pierdem.',
    '**EMOTIILE SUNT SUPRAEVALUATE**\nceea ce defineste experientele noastre pozitive va defini si experientele negative.',
    '**ALEGETI-VA LUPTA**\nfericirea presupune lupta. fericirea se dezvolta din probleme.',
    '**ALEGETI-VA LUPTA**\nla realizarile adevarate si de lunga durata se ajunge printr-un efort sustinut.',
    '**ALEGETI-VA LUPTA**\nca sa castigi trebuie sa joci.',
    '**ALEGETI-VA LUPTA**\ncalea spre fericire e plina de lucruri dureroase si stanjenitoare.',
    '**ALEGETI-VA LUPTA**\nceva tot trebuie sa alegi. nu poti trai o viata scutita de durere.',
    '**ALEGETI-VA LUPTA**\ndurerea este o intrebare interesanta. care e durerea pe care vrei s-o infrunti? asta s intrebarea grea, intrebarea care conteaza si care te va duce undeva.',
    '**ALEGETI-VA LUPTA**\nidentitatea ta este definita de luptele pe care esti dispus sa ti le asumi.',
    '**ALEGETI-VA LUPTA**\nsuccesul nostru este determinat de cat suntem dispusi sa luptam pentru el.',
    '**ALEGETI-VA LUPTA**\nproblemele noastre sunt sursa fericirii noastre, precum si sursa unor probleme ceva mai usoare si mai actualizate.',
]